<a href="https://colab.research.google.com/github/karalavo/develop/blob/main/add_zeros.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Add zeros

`numpy`

### Условие
Реализуйте функцию, которая на вход принимает вектор ```x```, а возвращает вектор со вставленными нулями между числами.

Например, из ```[1, -5, 3]``` получить ```[1, 0, -5, 0, 3]```

### Замечания

* нельзя использовать циклы (ключевые слова for и while), list comprehension, map и т.п.


In [ ]:
import typing as tp
import numpy as np

In [4]:
def add_zeros(array: np.ndarray) -> tp.Optional[float]:
    array_trans = array.T
    array_zero = np.zeros_like(array_trans)
    duo_matrix = np.column_stack((array_trans, array_zero)).ravel()
    return duo_matrix[:-1]

In [5]:
print(add_zeros(array=np.array([1, 2, 3])))
print(add_zeros(array=np.array([])))
print(add_zeros(array=np.array([1])))
print(add_zeros(array=np.array([1, 1])))
print(add_zeros(array=np.array([0])))
print(add_zeros(array=np.array([1, 0, 0, 1])))
print(add_zeros(array=np.zeros(10)))

[1 0 2 0 3]
[]
[1]
[1 0 1]
[0]
[1 0 0 0 0 0 1]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
